name: Build Trakt against master version of Rocq

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v5
      - uses: nixbuild/nix-quick-install-action@v34

      - name: Build against master
        run: |
          nix build --impure --expr '
            let
              flake = builtins.getFlake (toString ./.);
              pkgs = import flake.inputs.nixpkgs {
                system = "x86_64-linux";
                overlays = [ flake.overlays.trakt ];
              };
            in
            flake.lib.mkTrakt pkgs {
              rocq-version = "master";
              stdlib-version = "master";
              rocq-elpi-version = "master";
            }' --print-build-logs
