name: Build Trakt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Allow to purge the cache

    steps:
      - uses: actions/checkout@v5
      - uses: nixbuild/nix-quick-install-action@v34

      - uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/flake.lock') }}
          gc-max-store-size: 1G
          purge: true

      - name: Build
        run: nix build .#trakt --print-build-logs

      - name: Build the whole matrix
        run: nix flake check --impure --print-build-logs
