name: Build Trakt against specific versions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
    inputs:
      rocq-version:
        default: "master"
        description: "Rocq version or commit"
        required: true
      stdlib-version:
        default: "master"
        description: "Stdlib version or commit"
        required: true
      rocq-elpi-version:
        default: "master"
        description: "Rocq-Elpi version or commit"
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v5
      - uses: nixbuild/nix-quick-install-action@v34

      - name: Build against specific versions
        run: |
          nix build --impure --expr '
            let
              flake = builtins.getFlake (toString ./.);
              pkgs = import flake.inputs.nixpkgs {
                system = "x86_64-linux";
                overlays = [ flake.overlays.trakt ];
              };
            in
            flake.lib.mkTrakt pkgs {
              rocq-version = "${{ inputs.rocq-version || 'master' }}";
              stdlib-version = "${{ inputs.stdlib-version || 'master' }}";
              rocq-elpi-version = "${{ inputs.rocq-elpi-version || 'master' }}";
            }' --print-build-logs
