name: Build Trakt against supported released versions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  discover:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.discover.outputs.packages }}

    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35

      - name: Get all versions
        id: discover
        run: |
          packages=$(nix eval --json .#checks.x86_64-linux --apply builtins.attrNames)
          echo "packages=$packages" >> "$GITHUB_OUTPUT"

  matrix:
    needs: discover
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ${{ fromJSON(needs.discover.outputs.packages) }}

    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35

      - uses: ryanccn/attic-action@v0
        with:
          cache: smtcoq
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Build specific version
        run: nix build .#checks.x86_64-linux.${{ matrix.package }} --print-build-logs
