name: Build Trakt against reverse dependencies

on:
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  reverse:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - repository: github:SMTCoq/SMTCoq
          - repository: github:SMTCoq/Sniper
            path: SMTCoq/trakt

    steps:
      - uses: actions/checkout@v7
      - uses: nixbuild/nix-quick-install-action@v35

      - uses: ryanccn/attic-action@v0
        with:
          cache: smtcoq
          endpoint: ${{ secrets.ATTIC_ENDPOINT }}
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Build reverse dependency
        run: nix build ${{ matrix.repository }} --override-input ${{ matrix.path || 'trakt' }} . --print-build-logs

  reverse-success:
    if: ${{ always() }}
    needs: reverse
    runs-on: ubuntu-latest

    steps:
      - name: Has the matrix failed?
        if: ${{ needs.reverse.result != 'success' }}
        run: exit 1
